; Death Timer - Immersive Bleedout_FLM.ini

; CACO Potions of Blood Ingestibles
FormList = ANDR_KO_FLST_GivePotion|MagicAlchBloodEffect_CACO

; CACO Potions of Blood Effects
FormList = ANDR_KO_FLST_VampireHealOnlyEffects|DLC1AlchRestoreHealthBlood_1sec,DLC1AlchRestoreHealthBlood_5sec,DLC1AlchRestoreHealthBlood_10sec

; Exclude Vokrii cloak restoration perk "Inspire"
FormList = ANDR_KO_FLST_RecoverEffectExclusions|VKR_Res_Inspire_Effect_CloakProc,VKR_Res_Inspire_Effect_CloakProc_LingeringRestoreHealth,VKR_Res_Inspire_Effect_CloakProc_Respite
